### ISSUE TITLE
getLen计算当前数据长度问题

### ISSUE THREAD

**Issue by ZhaoZhijie** [play175/ExBuffer#14]
getLen获取数据长度貌似有问题，如果一次put放入的数据长度恰好等于剩余空间那么不会扩展buffer，这个时候_putOffset和_readOffset会重合，通过getLen计算出来的当前数据长度会是0，而实际保存的数据长度应该是_buffer的长度，这会导致之后的解包都出现异常。

**Comment by play175** [comment]
你好 ，可以把你的测试代码贴出来吗？

**Comment by ZhaoZhijie** [comment]
var ExBuffer = require("ExBuffer");

var exBuffer = new ExBuffer().uint32Head().bigEndian();
exBuffer.on('data', function(buf){
    console.log("收到数据，内容长度="+buf.length);
});

//构造2个包 一个包36字节 一个包536字节 包头用4字节
var arr1 = new Array(40);
var buf1 = new Buffer(arr1);
buf1.writeUInt32BE(36, 0);

var arr2 = new Array(540);
var buf2 = new Buffer(arr2);
buf2.writeUInt32BE(536, 0);

var buf = Buffer.concat([buf1, buf2]);

//buf一共580字节 将其分成4截put
var sbuf1 = new Buffer(20);
var sbuf2 = new Buffer(60);
var sbuf3 = new Buffer(476);
var sbuf4 = new Buffer(24);
buf.copy(sbuf1, 0, 0, 20);   //长度20
buf.copy(sbuf2, 0, 20, 80);  //长度60
buf.copy(sbuf3, 0, 80, 556); //长度476
buf.copy(sbuf4, 0, 556, 580);//长度24

//按下面这种截断方式不会有问题 只要不触发read和put指针重合的情况
// var sbuf1 = new Buffer(20);
// var sbuf2 = new Buffer(60);
// var sbuf3 = new Buffer(456);
// var sbuf4 = new Buffer(44);
// buf.copy(sbuf1, 0, 0, 20);   //长度20
// buf.copy(sbuf2, 0, 20, 80);  //长度60
// buf.copy(sbuf3, 0, 80, 536); //长度456
// buf.copy(sbuf4, 0, 536, 580);//长度44

exBuffer.put(sbuf1);
exBuffer.put(sbuf2);    //本次put后第一个包解完，并且保存了第二个包部分数据
exBuffer.put(sbuf3);    //本次put后put指针和read指针重合
exBuffer.put(sbuf4);    //本次put第二个包本应解完 但是上一次put会使getLen计算出的长度为0而解不了

执行结果：
收到数据，长度=36

用注释部分执行的结果：
收到数据，长度=36
收到数据，长度=536

**Comment by play175** [comment]
你好，我增加了一个规则，保证尾部至少有一个位置永远空余，避免读写指针重叠，这样应该修复个问题了
