### ISSUE TITLE
var exBuffer = new ExBuffer().uint32Head().littleEndian();

### ISSUE THREAD

**Issue by zscorpio** [play175/ExBuffer#7]
貌似测试不过...
var ExBuffer = require('ExBuffer');
//构造一个ExBuffer，采用4个字节（uint32无符号整型）表示包长，而且是little endian 字节序
var exBuffer = new ExBuffer().uint32Head().littleEndian();
//或者构造一个ExBuffer，采用2个字节（ushort型）表示包长，而且是big endian 字节序 (默认)
// var exBuffer = new ExBuffer().ushortHead().bigEndian();

//只要收到满足的包就会触发事件
exBuffer.on('data',function(buffer){
    console.log('>> receive data,length:'+buffer.length);
    console.log(buffer);
});

//传入一个9字节长的数据，分多次put （对应于TCP中的分包的情况）
// exBuffer.put(new Buffer([0,9]));
// exBuffer.put(new Buffer([1,2,3,4,5,6,7]));
// exBuffer.put(new Buffer([8,9]));

//传入一个3个字节的数据和一个6个字节的数据，一次put（对应于TCP中的粘包的情况）
// exBuffer.put(new Buffer([0,3,1,2,3,0,6,1,2,3,4,5,6]));

exBuffer.put(new Buffer([0,0,0,1]));
exBuffer.put(new Buffer([1]));

**Comment by play175** [comment]
hi，请把报错输出贴出来

**Comment by zscorpio** [comment]
hello打扰了~
现在ok了,我知道了为什么,是大小端的问题,应该也用大端,小端这样出问题.
还有建议增加个方法,长度是否包含包头,我的包长是包含包头的,然后之前调试一直出错...如果你不想改,我可以提交各pull request哈

**Comment by kidbei** [comment]
hi,我在写一个node.js的rpc，使用了您的粘包解决方案。在我测试的过程中，我用客户端循环发送1000条数据，服务端原样返回，没有问题。但是当我循环发送10000条时，服务端就出现粘包现象了。同样的，我用setInterval定时发送10000条却没有问题。当然，这不一定是您的框架问题，我找了很久没找到原因，不知道可否验证一下是否存在这个问题。
![1](https://cloud.githubusercontent.com/assets/7855673/11356859/b1db133a-929c-11e5-983f-90893a7f938e.png)
![2](https://cloud.githubusercontent.com/assets/7855673/11356865/b960564c-929c-11e5-868f-a4904f86f132.png)
![3](https://cloud.githubusercontent.com/assets/7855673/11356866/b9a4938e-929c-11e5-973b-187713bf1622.png)
![4](https://cloud.githubusercontent.com/assets/7855673/11356867/b9fba304-929c-11e5-98b2-7880ec5b9d29.png)

**Comment by play175** [comment]
长度是不包含包头的，因为协议对外是透明的，应用层不需要知道协议细节~
