### ISSUE TITLE
socket连续发送存在粘包问题

### ISSUE THREAD

**Issue by kidbei** [play175/ExBuffer#9]
hi,我在写一个node.js的rpc，使用了您的粘包解决方案。在我测试的过程中，我用客户端循环发送1000条数据，服务端原样返回，没有问题。但是当我循环发送10000条时，服务端就出现粘包现象了。同样的，我用setInterval定时发送10000条却没有问题。当然，这不一定是您的框架问题，我找了很久没找到原因，不知道可否验证一下是否存在这个问题。
![1](https://cloud.githubusercontent.com/assets/7855673/11356859/b1db133a-929c-11e5-983f-90893a7f938e.png)
![2](https://cloud.githubusercontent.com/assets/7855673/11356865/b960564c-929c-11e5-868f-a4904f86f132.png)
![3](https://cloud.githubusercontent.com/assets/7855673/11356866/b9a4938e-929c-11e5-973b-187713bf1622.png)
![4](https://cloud.githubusercontent.com/assets/7855673/11356867/b9fba304-929c-11e5-98b2-7880ec5b9d29.png)

**Comment by play175** [comment]
我简单测试了一下，连续收1w个包没什么问题哦。
接受到exbuffer的data事件时，要马上把数据copy出来，因为马上这段缓存就会被新数据填充
